### PR TITLE
feat: pass controller to serialize / deserialize

### LINKED ISSUE #46: Accessing the controller / services
Would it hurt, if we were able to access the corresponding `Controller` from the `serialize` and `deserialize` methods?

I am asking primarily because I need to *synchronously* access the `store` service, in order to lookup a record for an ID. Basically something like this:

```js
new QueryParams({
  someModel: {
    defaultValue: null,

    serialize(model) {
      return model ? get(model, 'id') : '';
    },

    deserialize(id) {
      return id ? get(this, 'store').peekRecord('model-name', id) : null;
    }
});
```
Do you think this is a form of unhealthy entanglement, even though the lookup is guaranteed to work synchronously?

### PR DESCRIPTION
**Pull request by buschtoens**
Closes #46.

### CODE REVIEW

**Comment by offirgolan** [comment]
Thanks @buschtoens! 😄

**Comment by offirgolan** [comment]
Released with `v0.3.7`

**Comment by Turbo87** [comment]
@offirgolan @buschtoens it appears that this feature is actually somewhat broken. the thing that is getting passed to the `serialize/deserialize()` methods is the controller **prototype**, not the controller instance. that means that e.g. injected services on the controller cannot be looked up and trying to look them up will throw errors.

reverting https://github.com/offirgolan/ember-parachute/pull/25 might fix this, but apparently, that would cause other issues. any clues on how to solve this?

**Comment by buschtoens** [comment]
Oh, dang. Unfortunately I'm not currently using ember-parachute. :/

**Comment by Turbo87** [comment]
seems like this issue is similar to https://github.com/offirgolan/ember-parachute/issues/46#issuecomment-400651182 😢

**Comment by offirgolan** [comment]
@Turbo87 one solution is to pass `undefined` when we don't have the controller instance. That would be a breaking change but would also be safer. We could also try to serialize/deserialize only when the controller is ready but I'm unsure on what would be the resulting behavior.

**Pull request merged**
